theme: minima
minima:
  skin: dark
header_pages:
 - README.md
plugins:
- jekyll-remote-theme
title: Flovoko's HQ
description: Flovoko's HQ
author:
  name: Florian von Ko√ü
  email: "vonkossf@gmail.com"
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/Flovoko" }
